font:
  - file:
      type: gfonts
      family: IBM+Plex+Mono
      weight: 700
    id: clock_font
    size: 260
    bpp: 4

  - file:
      type: gfonts
      family: IBM+Plex+Mono
      weight: 700
    id: info_font
    size: 85
    bpp: 4

  - file:
      type: gfonts
      family: IBM+Plex+Mono
      weight: 700
    id: small_info_font
    size: 55
    bpp: 4

lvgl:
  style_definitions:
    - id: clock_style
      text_font: clock_font
      text_color: 0xDDDDDD
    - id: outdoor_style
      text_font: info_font
      text_color: 0x008001
    - id: small_outdoor_style
      text_font: small_info_font
      text_color: 0x008001
      opa: 0.7
    - id: indoor_style
      text_font: info_font
      text_color: 0xBDB76B
    - id: small_indoor_style
      text_font: small_info_font
      text_color: 0xBDB76B
      opa: 0.7
    - id: high_style
      text_font: info_font
      text_color: 0xFE0000
    - id: small_high_style
      text_font: small_info_font
      text_color: 0xFE0000
      opa: 0.7
    - id: low_style
      text_font: info_font
      text_color: 0x1F90FF
    - id: small_low_style
      text_font: small_info_font
      text_color: 0x1F90FF
      opa: 0.7
