# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 12
    bpp: 4
    glyphs: [
      "\U000F05A9",  # mdi-wifi
      "\U000F16B5",  # mdi-wifi-alert      
      ]

# Map icons to names
substitutions:
  wifi:      "\U000F05A9"
  wifialert: "\U000F16B5"
