# Backlight
output:
  - platform: ledc
    pin: GPIO06
    id: gpio_06

light:
  - platform: monochromatic
    output: gpio_06
    name: "Clock LR Backlight Dimming"

switch:
  - platform: gpio
    id: clock_lr_backlight
    pin: 
      ch422g: io_ex
      number: 2
    restore_mode: ALWAYS_ON
    internal: true