# Backlight
output:
  - platform: ledc
    pin: GPIO16
    id: backlight

light:
  - platform: monochromatic
    output: backlight
    name: ${uname} backlight
    restore_mode: ALWAYS_ON

switch:
  - platform: template
    name: ${uname} antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:

  - platform: gpio
    name: ${uname} bl binary
    pin: 
      ch422g: io_ex
      number: 2
    restore_mode: ALWAYS_ON
