# Backlight
output:
  - platform: ledc
    pin: GPIO06
    id: gpio_06

light:
  - platform: monochromatic
    output: gpio_06
    name: ${uname} backlight dimming

switch:
  - platform: gpio
    name: ${uname} backlight
    pin: 
      ch422g: io_ex
      number: 2
    restore_mode: ALWAYS_ON
    internal: true