sensor:
# Wifi Signal Strength
  - platform: wifi_signal
    name:  ${uname} wifi signal
    update_interval: 60s
    entity_category: diagnostic

button:
  - platform: restart
    name: ${uname} restart
  - platform: safe_mode
    name: ${uname} restart safe
    icon: mdi:restart-alert

binary_sensor:
  - platform: status
    name: ${uname} status
