sensor:
# Uptime
  - platform: uptime
    id: uptime_seconds
    internal: true

# Wifi Signal Strength
  - platform: wifi_signal
    name:  ${uname} wifi signal
    update_interval: 60s
    entity_category: diagnostic
