sensor:
# Wifi Signal Strength
  - platform: wifi_signal
    name:  ${uname} wifi signal
    update_interval: 60s
    entity_category: diagnostic

# Uptime
  - platform: uptime
    id: uptime_seconds
    internal: true

button:
  - platform: restart
    name: ${uname} restart
  - platform: safe_mode
    name: ${uname} restart safe
    icon: mdi:restart-alert

binary_sensor:
  - platform: status
    name: ${uname} status

text_sensor:
  - platform: template
    name: ${uname} uptime
    entity_category: diagnostic
    lambda: |-
      char s[20];
      char s_days[5];
      char s_hours[2];
      char s_seconds[2];
      char s_minutes[2];
      int seconds = (id(uptime_seconds).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      itoa(days, s_days, 10);
      itoa(hours, s_hours, 10);
      itoa(minutes, s_minutes, 10);
      itoa(seconds, s_seconds, 10);
      if ( days > 3650 ) {
        return { "Starting up" };
      }
      s[0] = '\0';
      if ( days ) {
        strcat(s, s_days);
        strcat(s, "d ");
      }
      if ( hours ) {
        strcat(s, s_hours);
        strcat(s, "h ");
      }
      if ( minutes ) {
        strcat(s, s_minutes);
        strcat(s, "m ");
      }
      if ( seconds ) {
        strcat(s, s_seconds);
        strcat(s, "s");
      }
      return { s };
    icon: mdi:clock-start
