sensor:
# Wifi Signal Strength
  - platform: wifi_signal
    name:  ${uname} wifi signal
    update_interval: 60s
    entity_category: diagnostic

# Uptime
  - platform: uptime
    id: uptime_seconds
    internal: true

text_sensor:
  - platform: template
    name: ${uname} uptime
    entity_category: diagnostic
    lambda: |-
      int seconds = (id(uptime_seconds).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days > 3650 ) {
        return { "Starting up" };
      } else if ( days ) {
        return { (itoa(days,10) +"d " + itoa(hours) +"h " + itoa(minutes) +"m "+ itoa(seconds) +"s").c_str(,10,10,10) };
      } else if ( hours ) {
        return { (itoa(hours) +"h " + itoa(minutes) +"m "+ itoa(seconds) +"s").c_str(,10,10,10) };
      } else if ( minutes ) {
        return { (itoa(minutes) +"m "+ itoa(seconds) +"s").c_str(,10,10) };
      } else {
        return { (itoa(seconds) +"s").c_str(,10) };
      }
    icon: mdi:clock-start
