sensor:
# Wifi Signal Strength
  - platform: wifi_signal
    name:  ${uname} wifi signal
    update_interval: 60s
    entity_category: diagnostic

# Uptime
  - platform: uptime
    id: uptime_seconds
    internal: true

text_sensor:
  - platform: template
    name: ${uname} uptime
    entity_category: diagnostic
    lambda: |-
      int seconds = (id(uptime_seconds).state);
      char s_days[5]
      char s_hours[2]
      char s_seconds[2]
      char s_minutes[2]
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      itoa(days, s_days, 10)
      itoa(hours, s_hours, 10)
      itoa(minutes, s_minutes, 10)
      itoa(seconds, s_seconds, 10)
      if ( days > 3650 ) {
        return { "Starting up" };
      } else if ( days ) {
        return { (s_days +"d " + s_hours +"h " + s_minutes +"m "+ s_seconds +"s").c_str(,10,10,10) };
      } else if ( hours ) {
        return { (s_hours +"h " + s_minutes +"m "+ s_seconds +"s").c_str(,10,10,10) };
      } else if ( minutes ) {
        return { (s_minutes +"m "+ s_seconds +"s").c_str(,10,10) };
      } else {
        return { s_seconds +"s").c_str(,10) };
      }
    icon: mdi:clock-start
