time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: /1 # Update every minute
        then:
          - script.execute: time_update    

# Clock
script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: display_time
          text: !lambda |-
            char clock[5];
            clock = id(homeassistant_time).now().strftime("%I:%M");
            if (clock[0] == 0) {
              return &clock[1];
            } else {
              return clock;
            };
