substitutions:
  name: default
  dname: ${name}-clk
  uname: ${name}_clk

esphome:
  name: ${dname}
  on_boot:
    priority: -100
    then:
      - lambda: |-
          id(homeassistant_time).update();
          id(sevenseg).update();

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: esp-idf

logger:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid_password

api:

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: /1 # Update every minute
        then:
          - lambda: |-
              id(homeassistant_time).update();
              id(sevenseg).update();
    on_time_sync:
      then:
        - lambda: |-
            id(homeassistant_time).update();
            id(sevenseg).update();

# setup display dimmer
number:
  - platform: template
    name: brightness
    id: brightness
    min_value: 0
    max_value: 7
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 4
    set_action:
      - lambda: |-
          id(sevenseg).update();

display:
  - platform: tm1637
    id: sevenseg
    clk_pin: GPIO35
    dio_pin: GPIO37
    intensity: 4
    lambda: |-
      it.set_intensity(id(brightness).state);
      it.strftime("%H.%M", id(homeassistant_time).now());

button:
  - platform: restart
    name: restart
  - platform: safe_mode
    name: restart safe
    icon: mdi:restart-alert

binary_sensor:
  - platform: status
    name: status

sensor:
  - platform: wifi_signal
    name:  wifi signal
    update_interval: 60s

