substitutions:
  # these are able to be overridden on the command line
  name: default
  pin: '18'
  delayed_off: '2s'
  # these can be left alone unless they really need to be changed
  dname: ${name}-pir
  uname: ${name}_pir

esphome:
  name: ${dname}

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf

# Enable logging
logger:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid_password

api:
  reboot_timeout: 5min

button:
  - platform: restart
    name: restart
  - platform: safe_mode
    name: restart safe
    icon: mdi:restart-alert

# setup sensors
binary_sensor:
  - platform: gpio
    pin: ${pin}
    name: motion
    device_class: motion
    filters:
      - delayed_off: ${delayed_off}
  - platform: status
    name: status

sensor:
  - platform: wifi_signal
    name:  wifi signal
    update_interval: 60s
