substitutions:
  # the first is meant to be overridden on the command line
  name: default
  # these can be left alone unless they really need to be changed
  dname: ${name}-s31
  uname: ${name}_s31

esphome:
  name: ${dname}
  
esp8266:
  board: esp01_1m
  early_pin_init: false

api:
  reboot_timeout: 5min

ota:
  platform: esphome

# Disable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

time:
  - platform: sntp
    id: the_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid_password

# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800

button:
  - platform: restart
    name: ${name} restart
  - platform: safe_mode
    name: ${uname} restart safe
    icon: mdi:restart-alert

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${name} button
    on_press:
      - switch.toggle: ${uname}_relay
  - platform: status
    name: ${name} status

sensor:
  - platform: wifi_signal
    name:  ${name} wifi signal
    update_interval: 60s
  - platform: uptime
    id: uptime_seconds
    internal: true
  - platform: cse7766
    current:
      name: ${name} current
      accuracy_decimals: 1
    voltage:
      name: ${name} voltage
      accuracy_decimals: 1
    power:
      name: ${name} power
      accuracy_decimals: 1
      id: ${uname}_power
  - platform: total_daily_energy
    name: ${name} daily energy
    power_id: ${uname}_power

text_sensor:
  - platform: template
    name: ${uname} uptime
    entity_category: diagnostic
    lambda: |-
      int seconds = (id(uptime_seconds).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days > 3650 ) {
        return { "Starting up" };
      } else if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else {
        return { (String(seconds) +"s").c_str() };
      }
    icon: mdi:clock-start

switch:
  - platform: gpio
    name: ${name}  relay
    pin: GPIO12
    id: ${uname}_relay
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: True