substitutions:
  # the first is meant to be overridden on the command line
  name: default
  # these can be left alone unless they really need to be changed
  dname: ${name}-s31
  uname: ${name}_s31

esphome:
  name: ${dname}
  
esp8266:
  board: esp01_1m
  early_pin_init: false
  framework:
    type: esp-idf

api:
  reboot_timeout: 5min

ota:
  platform: esphome

# Disable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid_password

# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

time:
  - platform: homeassistant
    id: the_time

button:
  - platform: restart
    name: restart
  - platform: safe_mode
    name: restart safe
    icon: mdi:restart-alert

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: status

sensor:
  - platform: wifi_signal
    name:  wifi signal
    update_interval: 60s
  - platform: cse7766
    current:
      name: current
      accuracy_decimals: 1
    voltage:
      name: voltage
      accuracy_decimals: 1
    power:
      name: power
      accuracy_decimals: 1
      id: power
  - platform: total_daily_energy
    name: daily energy
    power_id: power

switch:
  - platform: gpio
    name:  relay
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: True