lvgl:
  pages:
    - id: main_page
      layout: 
        type: flex
        flex_flow: column_wrap
      width: 100%
      bg_color: Black
      bg_opa: cover

      widgets:
      
        # Clock
        - label:
            text: "--:--"
            id: display_time
            styles: clock_style
            align: top_mid
            x: 0
            y: 5
            text_align: center
  
        # Outdoor
        - obj:
            border_width: 0
            pad_all: 0px
            align: bottom_left
            x: 5
            y: -95
            width: 140
            height: 90
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: left
                flex_align_cross: end
                pad_column: 2px
                pad_row: 0px
            widgets:
              - label:
                  text: " "
                  id: outdoor_temperature
                  styles: info_style
                  text_align: left
              - label:
                  styles: small_outdoor_style
                  text: 째F
                  text_align: left
        - obj:
            border_width: 0
            pad_all: 0px
            align: bottom_left
            x: 5
            y: -5
            width: 140
            height: 90
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: left
                flex_align_cross: end
                pad_column: 2px
                pad_row: 0px
            widgets:
              - label:
                  text: " "
                  id: outdoor_humidity
                  styles: outdoor_style
                  text_align: left
              - label:
                  styles: small_outdoor_style
                  text: "%"
                  text_align: left
  
        # Forecast
        - obj:
            border_width: 0
            pad_all: 0px
            align: bottom_mid
            x: 0
            y: -95
            width: 140
            height: 90
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: left
                flex_align_cross: end
                pad_column: 2px
                pad_row: 0px
            widgets:
              - label:
                  text: " "
                  id: today_high
                  styles: high_style
                  text_align: left
              - label:
                  styles: small_high_style
                  text: 째F
                  text_align: left
        - obj:
            border_width: 0
            pad_all: 0px
            align: bottom_mid
            x: 0
            y: -5
            width: 140
            height: 90
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: left
                flex_align_cross: end
                pad_column: 2px
                pad_row: 0px
            widgets:
              - label:
                  text: " "
                  id: today_low
                  styles: low_style
                  text_align: left
              - label:
                  styles: small_low_style
                  text: 째F
                  text_align: left
  
        # Indoor
        - obj:
            border_width: 0
            pad_all: 0px
            align: bottom_right
            x: -5
            y: -95
            width: 140
            height: 90
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: left
                flex_align_cross: end
                pad_column: 2px
                pad_row: 0px
            widgets:
              - label:
                  text: " "
                  id: indoor_temperature
                  styles: indoor_style
                  text_align: left
              - label:
                  styles: small_indoor_style
                  text: 째F
                  text_align: left
        - obj:
            border_width: 0
            pad_all: 0px
            align: bottom_right
            x: -5
            y: -5
            width: 140
            height: 90
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: left
                flex_align_cross: end
                pad_column: 2px
                pad_row: 0px
            widgets:
              - label:
                  text: " "
                  id: indoor_humidity
                  styles: indoor_style
                  text_align: left
              - label:
                  styles: small_indoor_style
                  text: "%"
                  text_align: left
  