lvgl:
  pages:
    - id: main_page
      width: 100%
      bg_color: Black

      widgets:
      
        # Clock
        - label:
            text: "--:--"
            id: display_time
            styles: clock_style
            align: top_mid
            x: 0
            y: -40
            text_align: center

        # Outdoor
        - obj:
            scrollbar_mode: "OFF"
            border_width: 0
            pad_all: 0px
            align: bottom_left
            x: 15
            y: -115
            width: 240
            height: 100
            bg_color: Black
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: start
                flex_align_cross: end
                pad_column: 0px
                pad_row: 0px
            widgets:
              - label:
                  text: "--"
                  id: outdoor_temperature
                  styles: outdoor_style
                  text_align: left
              - label:
                  text: ${tempscale}
                  styles: small_outdoor_style
                  text_align: left
        - obj:
            scrollbar_mode: "OFF"
            border_width: 0
            pad_all: 0px
            align: bottom_left
            x: 15
            y: -5
            width: 240
            height: 100
            bg_color: Black
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: start
                flex_align_cross: end
                pad_column: 0px
                pad_row: 0px
            widgets:
              - label:
                  text: "--"
                  id: outdoor_humidity
                  styles: outdoor_style
                  text_align: left
              - label:
                  styles: small_outdoor_style
                  text: "%"
                  text_align: left
  
        # Forecast
        - obj:
            scrollbar_mode: "OFF"
            border_width: 0
            pad_all: 0px
            align: bottom_mid
            x: 0
            y: -115
            width: 240
            height: 100
            bg_color: Black
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: center
                flex_align_cross: end
                pad_column: 0px
                pad_row: 0px
            widgets:
              - label:
                  text: "--"
                  id: today_high
                  styles: high_style
                  text_align: left
              - label:
                  styles: small_high_style
                  text: ${tempscale}
                  text_align: left
        - obj:
            scrollbar_mode: "OFF"
            border_width: 0
            pad_all: 0px
            align: bottom_mid
            x: 0
            y: -25
            width: 240
            height: 100
            bg_color: Black
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: center
                flex_align_cross: end
                pad_column: 0px
                pad_row: 0px
            widgets:
              - label:
                  text: "--"
                  id: today_low
                  styles: low_style
                  text_align: left
              - label:
                  styles: small_low_style
                  text: ${tempscale}
                  text_align: left
  
        # Indoor
        - obj:
            scrollbar_mode: "OFF"
            border_width: 0
            pad_all: 0px
            align: bottom_right
            x: -15
            y: -115
            width: 240
            height: 90
            bg_color: Black
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: end
                flex_align_cross: end
                pad_column: 0px
                pad_row: 0px
            widgets:
              - label:
                  text: "--"
                  id: indoor_temperature
                  styles: indoor_style
                  text_align: left
              - label:
                  styles: small_indoor_style
                  text: ${tempscale}
                  text_align: left
        - obj:
            scrollbar_mode: "OFF"
            border_width: 0
            pad_all: 0px
            align: bottom_right
            x: -15
            y: -25
            width: 240
            height: 100
            bg_color: Black
            layout:
                type: FLEX
                flex_flow: ROW_WRAP
                flex_align_main: end
                flex_align_cross: end
                pad_column: 0px
                pad_row: 0px
            widgets:
              - label:
                  text: "--"
                  id: indoor_humidity
                  styles: indoor_style
                  text_align: left
              - label:
                  styles: small_indoor_style
                  text: "%"
                  text_align: left
  